[project]
name = "espnow2mqtt-gateway"
version = "0.1.0"
description = "Gateway for custom ESPNow Devices."
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "aiomqtt>=2.4.0",
    "aioserial>=1.3.1",
]